### ISSUE TITLE
Issue-1-user-can-search-for-art

### ISSUE THREAD

**Issue by mgmauriello** [mgmauriello/youseum#1]
## 💰 Motivation

Ability to have search bar activity

## 📐 Plan

Create form for submitting a search request to the API

## 🖼️ Wireframes
<img width="643" alt="Screen Shot 2022-02-28 at 7 13 16 PM" src="https://user-images.githubusercontent.com/97134047/156097962-3a6a6ba3-58cd-469c-bcc7-36174aa79d28.png">

## ✅ Task List

- [x] Create basic page layout with background color and navbar.
- [x] Create visibility and styling for search bar.
- [x] Add icons to HTML and CSS.
- [x] Create button to submit the search.
- [x] Begin planning data-view for different elements to show different results ie [data-view=”search-results”].
- [x] Clear search when submit is executed.
- [x] Remove or comment out all CSS styling that had no effect or was otherwise unnecessary.
- [x] Fix all errors.
