### ISSUE TITLE
Issue-2-user-can-view-search-results

### ISSUE THREAD

**Issue by mgmauriello** [mgmauriello/youseum#2]
## 💰 Motivation

Ability to retrieve results based on search 

## 📐 Plan

Utilize the API to display objects specific to the search results

## 🖼️ Wireframes
![Screen Shot 2022-03-01 at 12 22 11 PM](https://user-images.githubusercontent.com/97134047/156243036-cf97d0d7-74a8-4a5d-8016-8137f8ff9a63.png)

## ✅ Task List
- [x] Add some dummy entries in the HTML and style them to match the wireframe under the div[data-view="search-results"].
- [x]  Add some dummy search results to the unordered list in the HTML and style them to match the wireframe.
- [x]  Check that the results list looks good on both mobile and desktop screens.
- [x]  Define a function that takes a single result object and returns a DOM tree that matches one of the example results in the HTML.
- [x]  Use a loop to create a DOM tree for each search result in the data model and append it to the page when the 'DOMContentLoaded' event is fired.
- [x]  Remove the example HTML result once entries are successfully appended to the DOM on page load.
- [x]  Add a navigation item to the navbar to go back to div[data-view="search-page"] .
- [x]  Check search functionality.
- [x]  Check page refresh to show the same view as before.
