### ISSUE TITLE
Issue-3-user-can-view-art-details

### ISSUE THREAD

**Issue by mgmauriello** [mgmauriello/youseum#3]
## 💰 Motivation

Ability to view specific details of the object in the Walters Art Museum Collection

## 📐 Plan
Utilize the API to display the descriptions of the objects selected by user.

## 🖼️ Wireframes
<img width="1148" alt="Screen Shot 2022-03-01 at 10 30 48 PM" src="https://user-images.githubusercontent.com/97134047/156307747-751cce85-d5bd-44f4-b971-295cc7759302.png">

## ✅ Task List

- [x] Add some dummy entry in the HTML and style them to match the wireframe under the div[data-view="result-descriptions"].
- [x] create styling for the objects img, title, creator, the medium + dimensions, dateText, and description.
- [x] add heart icon to the bottom corner and my collections button to the navbar to be used in feat 4
- [x] add click event listener for the .card in the results page to commence view swap to [data-view="result-descriptions"].
- [x] add click event listener to the back arrow and heading to commence view swap to [data-view="search-results"].
- [x] check functionality.
- [x] fix errors!

**Comment by mgmauriello** [comment]
hey Michaela, keep it simple for now. If time, add more to this! Good work!
