### ISSUE TITLE
Issue-4-user-can-add-art-to-their-collection

### ISSUE THREAD

**Issue by mgmauriello** [mgmauriello/youseum#4]
## 💰 Motivation

Ability to add selected pieces of art to the users own personal collection via a favoriting system.

## 📐 Plan
Selected pieces are added to the data-view dedicated for the user's personal collection.
---

## 🖼️ Wirefra
<img width="684" alt="Screen Shot 2022-03-03 at 5 10 22 PM" src="https://user-images.githubusercontent.com/97134047/156679954-30319d50-038b-4da3-900e-15e4ed747d26.png">
mes

<img width="684" alt="Screen Shot 2022-03-03 at 5 10 40 PM" src="https://user-images.githubusercontent.com/97134047/156679920-2ab93012-e4ee-4d35-93e4-e26f8ba7921c.png">

## ✅ Task List
- [x]  Create the heart/favorite icon.
- [x]  Create the 'My Collection' button in the navbar
- [x]  When heart is clicked, added result to the data model without changing the page
- [x]  Change the empty heart to filled heart if item is added to the collection.
- [x]  Make sure that heart click targets show a cursor: pointer when hovered with the mouse.
- [x] Create sibling [data-view] for the collection.
- [x] Display similar to the result page for the pieces in the collection. 
- [x] Can view saved items in the collection data-view.
- [x] fix errors!!

**Comment by mgmauriello** [comment]
Good work, Michaela! Keep it up!
