### ISSUE TITLE
Issue-5-user-can-remove-art-from-their-collection

### ISSUE THREAD

**Issue by mgmauriello** [mgmauriello/youseum#5]
## 💰 Motivation

Ability to remove saved pieces of art from their personal collection.

## 📐 Plan
Allow users to delete an entry from its display screen.

----
## 🖼️ Wireframes
![Screen Shot 2022-03-03 at 5 27 25 PM](https://user-images.githubusercontent.com/97134047/156681560-71c35611-e1ca-4cb2-b4be-9875019dd96d.png)
![Screen Shot 2022-03-03 at 5 27 37 PM](https://user-images.githubusercontent.com/97134047/156681569-6989437f-36e8-43ac-b160-3ec49e0c7784.png)
![Screen Shot 2022-03-03 at 5 27 44 PM](https://user-images.githubusercontent.com/97134047/156681573-5d3c6ac5-dcbe-4d41-a4c6-17142ddd9204.png)

## ✅ Task List

- [x]  Add a click target for deleting an entry to the entry form that only appears if the user is editing an entry.
- [x]  Show a confirmation modal when the user clicks the Delete Entry click target.
- [x]  Hide the modal if the user clicks Cancel.
- [x]  Remove the entry from the data model and the entry's DOM tree from the page if the user clicks Delete.
- [x]  Show the Entries list if the user clicks Delete.
- [x]  Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x]  Test all functionality again in a private browsing session.
- [x]  Fix all errors.
